language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=.1.*
  - LARAVEL_VERSION=.2.*
  - LARAVEL_VERSION=.3.*
  - LARAVEL_VERSION=.4.*
  - LARAVEL_VERSION=.5.*
  - LARAVEL_VERSION=.6.*
  - LARAVEL_VERSION=.7.*
  - LARAVEL_VERSION=.8.*

matrix:
  exclude:
    - php: 7.0
      env: LARAVEL_VERSION=.5.*
    - php: 7.0
      env: LARAVEL_VERSION=.6.*
    - php: 7.0
      env: LARAVEL_VERSION=.7.*
    - php: 7.0
      env: LARAVEL_VERSION=.8.*

before_script:
  - composer install --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "orchestra/testbench:3${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script: vendor/bin/phpunit